version: "3.9"

services:
  app:
    # build: .
    image: wglabz/hnms:latest
    container_name: hnms-monolith
    # Use host networking on Linux for best Nmap results
    network_mode: "host" 
    # ports:
    #   - "8000:8000"
    environment:
      APP_ENV: production
      APP_DEBUG: "False"
      DB_PATH: /data/network_scanner.duckdb
      DB_SCHEMA_PATH: app/schema.sql
      DB_INIT_MODE: create
      WORKERS: "1"
    volumes:
      - scanner-data:/data
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 512M
    restart: unless-stopped

  agent:
    image: portainer/agent:2.19.4
    container_name: portainer_agent
    environment:
      # Required if connecting to a remote Portainer instance
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"
    restart: always

volumes:
  scanner-data:
